### ISSUE TITLE
Dataflows init not working

### ISSUE THREAD

**Issue by higorspinto** [datopian/zen-of-data#6]
I'm trying to use dataflows init:

```
dataflows init http://www.nber.org/data/chat/FinalCHAT_72909.csv
```

I'm getting this error:

```
An error was found, but returning just with the version: No module named 'fcntl'
```

Dataflows was installed using pip.

```
pip install dataflows
```

Traceback:

```
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\data-flows\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\envs\data-flows\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\data-flows\Scripts\dataflows.exe\__main__.py", line 4, in <module>
  File "c:\programdata\anaconda3\envs\data-flows\lib\site-packages\dataflows\cli.py", line 9, in <module>
    from inquirer import themes
  File "c:\programdata\anaconda3\envs\data-flows\lib\site-packages\inquirer\themes.py", line 5, in <module>
    from blessings import Terminal
  File "c:\programdata\anaconda3\envs\data-flows\lib\site-packages\blessings\__init__.py", line 7, in <module>
    from fcntl import ioctl
ModuleNotFoundError: No module named 'fcntl'
```
My environment:

Python 3.7 (Anaconda)
Windows 10

Seems that fcntl module doesn't work on windows.
https://stackoverflow.com/questions/1422368/fcntl-substitute-on-windows

**Comment by RobGrootjen** [comment]
@higorspinto I got the same problem. 
But instead of  ```fcnt1``` I got ```_curses```

Heres mine 
```C:\Users\Agent 1>dataflows init http://www.nber.org/data/chat/FinalCHAT_72909.csv
An error was found, but returning just with the version: No module named '_curses'
Traceback (most recent call last):
  File "c:\users\agent 1\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\agent 1\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Agent 1\Anaconda3\Scripts\dataflows.exe\__main__.py", line 5, in <module>
  File "c:\users\agent 1\anaconda3\lib\site-packages\dataflows\cli.py", line 9, in <module>
    from inquirer import themes
  File "c:\users\agent 1\anaconda3\lib\site-packages\inquirer\themes.py", line 5, in <module>
    from blessings import Terminal
  File "c:\users\agent 1\anaconda3\lib\site-packages\blessings\__init__.py", line 5, in <module>
    import curses
  File "c:\users\agent 1\anaconda3\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
```

**Comment by RobGrootjen** [comment]
I just ran ```pip install windows-curses```

Got it resolved. Now I have exactly the same issue as yours with ```fcnt1```
Ill let you know if I find a solution

**Comment by higorspinto** [comment]
> I just ran `pip install windows-curses`
> 
> Got it resolved. Now I have exactly the same issue as yours with `fcnt1`
> Ill let you know if I find a solution

Same steps here.
